/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestAppImport } from './routes/test/app'
import { Route as TestAppNestedImport } from './routes/test/app/nested'
import { Route as TestAppIndexImport } from './routes/test/app/index'
import { Route as TestAppNestedFirstImport } from './routes/test/app/nested/first'
import { Route as TestAppNestedSecondImport } from './routes/test/app/nested/second'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TestAppRoute = TestAppImport.update({
  path: '/test/app',
  getParentRoute: () => rootRoute,
} as any)

const TestAppNestedRoute = TestAppNestedImport.update({
  path: '/nested',
  getParentRoute: () => TestAppRoute,
} as any)

const TestAppIndexRoute = TestAppIndexImport.update({
  path: '/',
  getParentRoute: () => TestAppRoute,
} as any)

const TestAppNestedFirstRoute = TestAppNestedFirstImport.update({
  path: '/first',
  getParentRoute: () => TestAppNestedRoute,
} as any)

const TestAppNestedSecondRoute = TestAppNestedSecondImport.update({
  path: '/second',
  getParentRoute: () => TestAppNestedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/test/app': {
      preLoaderRoute: typeof TestAppImport
      parentRoute: typeof rootRoute
    }
    '/test/app/nested': {
      preLoaderRoute: typeof TestAppNestedImport
      parentRoute: typeof TestAppImport
    }
    '/test/app/': {
      preLoaderRoute: typeof TestAppIndexImport
      parentRoute: typeof TestAppImport
    }
    '/test/app/nested/first': {
      preLoaderRoute: typeof TestAppNestedFirstImport
      parentRoute: typeof TestAppNestedImport
    }
    '/test/app/nested/second': {
      preLoaderRoute: typeof TestAppNestedSecondImport
      parentRoute: typeof TestAppNestedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  TestAppRoute.addChildren([
    TestAppNestedRoute.addChildren([
      TestAppNestedFirstRoute,
      TestAppNestedSecondRoute,
    ]),
    TestAppIndexRoute,
  ]),
])

/* prettier-ignore-end */
